local gamedataPerkType = {}

local _gamedataPerkType = {
    { "bulletjock", "Assault_Area_01_Perk_1", 0 },
    { "eagleeye", "Assault_Area_01_Perk_2", 1 },
    { "coveringkillshot", "Assault_Area_02_Perk_1", 2 },
    { "toocloseforcomfort", "Assault_Area_02_Perk_2", 3 },
    { "bullseye", "Assault_Area_03_Perk_1", 4 },
    { "executioner", "Assault_Area_03_Perk_2", 5 },
    { "shootreloadrepeat", "Assault_Area_04_Perk_1", 6 },
    { "duckhunter", "Assault_Area_04_Perk_2", 7 },
    { "nervesofsteel", "Assault_Area_05_Perk_1", 8 },
    { "feeltheflow", "Assault_Area_05_Perk_2", 9 },
    { "trenchwarfare", "Assault_Area_06_Perk_1", 10 },
    { "huntershands", "Assault_Area_06_Perk_2", 11 },
    { "skullskipper", "Assault_Area_07_Perk_1", 12 },
    { "namedbullets", "Assault_Area_07_Perk_2", 13 },
    { "bunker", "Assault_Area_08_Perk_1", 14 },
    { "recoilwrangler", "Assault_Area_08_Perk_2", 15 },
    { "inperspective", "Assault_Area_09_Perk_1", 16 },
    { "longshot", "Assault_Area_09_Perk_2", 17 },
    { "savagestoic", "Assault_Area_10_Perk_1", 18 },

    { "regeneration", "Athletics_Area_01_Perk_1", 19 },
    { "packmule", "Athletics_Area_01_Perk_2", 20 },
    { "invincible", "Athletics_Area_02_Perk_1", 21 },
    { "truegrit", "Athletics_Area_02_Perk_2", 22 },
    { "epimorphosis", "Athletics_Area_03_Perk_1", 23 },
    { "softonyourfeet", "Athletics_Area_03_Perk_2", 24 },
    { "steelandchrome", "Athletics_Area_04_Perk_1", 25 },
    { "gladiator", "Athletics_Area_04_Perk_2", 26 },
    { "dividedandattention", "Athletics_Area_05_Perk_1", 27 },
    { "multitasker", "Athletics_Area_05_Perk_2", 28 },
    { "likeabutterfly", "Athletics_Area_05_Perk_3", 29 },
    { "transporter", "Athletics_Area_06_Perk_1", 30 },
    { "strongertogether", "Athletics_Area_06_Perk_2", 31 },
    { "cardiocure", "Athletics_Area_06_Perk_3", 32 },
    { "humanshield", "Athletics_Area_07_Perk_1", 33 },
    { "marathoner", "Athletics_Area_07_Perk_2", 34 },
    { "dogofwar", "Athletics_Area_08_Perk_1", 35 },
    { "wolverine", "Athletics_Area_08_Perk_2", 36 },
    { "steelshell", "Athletics_Area_09_Perk_1", 37 },
    { "therock", "Athletics_Area_10_Perk_1", 38 },
    { "indestructable", "Athletics_Area_10_Perk_2", 39 },

    { "flurry", "Brawling_Area_01_Perk_1", 40 },
    { "crushingblows", "Brawling_Area_01_Perk_2", 41 },
    { "juggernaut", "Brawling_Area_02_Perk_1", 42 },
    { "dazed", "Brawling_Area_02_Perk_2", 43 },
    { "rush", "Brawling_Area_03_Perk_1", 44 },
    { "efficientblows", "Brawling_Area_03_Perk_2", 45 },
    { "humanfortress", "Brawling_Area_04_Perk_1", 46 },
    { "opportunestrike", "Brawling_Area_04_Perk_2", 47 },
    { "payback", "Brawling_Area_05_Perk_1", 48 },
    { "reinvigorate", "Brawling_Area_05_Perk_2", 49 },
    { "breathingspace", "Brawling_Area_06_Perk_1", 50 },
    { "relentless", "Brawling_Area_06_Perk_2", 51 },
    { "frenzy", "Brawling_Area_07_Perk_1", 52 },
    { "thrash", "Brawling_Area_07_Perk_2", 53 },
    { "bidingtime", "Brawling_Area_08_Perk_1", 54 },
    { "unshakable", "Brawling_Area_08_Perk_2", 55 },

    { "coldblood", "ColdBlood_Area_01_Perk_1", 56 },
    { "willtosurvive", "ColdBlood_Area_02_Perk_1", 57 },
    { "icyveins", "ColdBlood_Area_02_Perk_2", 58 },
    { "criticalconditoin", "ColdBlood_Area_03_Perk_1", 59 },
    { "frostysynapses", "ColdBlood_Area_03_Perk_2", 60 },
    { "defensiveclothing", "ColdBlood_Area_04_Perk_1", 61 },
    { "rapidbloodflow", "ColdBlood_Area_04_Perk_2", 62 },
    { "coldestblood", "ColdBlood_Area_05_Perk_1", 63 },
    { "frozenprecision", "ColdBlood_Area_05_Perk_2", 64 },
    { "predator", "ColdBlood_Area_06_Perk_1", 65 },
    { "bloodbrawl", "ColdBlood_Area_06_Perk_2", 66 },
    { "quicktransfer", "ColdBlood_Area_06_Perk_3", 67 },
    { "bloodswell", "ColdBlood_Area_07_Perk_1", 68 },
    { "coldandcalculating", "ColdBlood_Area_07_Perk_2", 69 },
    { "coolagulant", "ColdBlood_Area_08_Perk_1", 70 },
    { "unbreakable", "ColdBlood_Area_08_Perk_2", 71 },
    { "painisanillusion", "ColdBlood_Area_09_Perk_1", 72 },
    { "immunity", "ColdBlood_Area_10_Perk_1", 73 },

    { "biosynergy", "CombatHacking_Area_01_Perk_1", 74 },
    { "bloodware", "CombatHacking_Area_01_Perk_2", 75 },
    { "forgetmenot", "CombatHacking_Area_02_Perk_1", 76 },
    { "ispy", "CombatHacking_Area_02_Perk_2", 77 },
    { "hackersmanual", "CombatHacking_Area_02_Perk_3", 78 },
    { "daisychain", "CombatHacking_Area_03_Perk_1", 79 },
    { "weaklink", "CombatHacking_Area_03_Perk_2", 80 },
    { "signalsupport", "CombatHacking_Area_04_Perk_1", 81 },
    { "subliminalmessage", "CombatHacking_Area_05_Perk_1", 82 },
    { "mnemonic", "CombatHacking_Area_06_Perk_1", 83 },
    { "diffusion", "CombatHacking_Area_06_Perk_2", 84 },
    { "schoolofhardhacks", "CombatHacking_Area_06_Perk_3", 85 },
    { "plague", "CombatHacking_Area_07_Perk_1", 86 },
    { "criticalerror", "CombatHacking_Area_08_Perk_1", 87 },
    { "hackeroverlord", "CombatHacking_Area_08_Perk_2", 88 },
    { "anamnesis", "CombatHacking_Area_09_Perk_1", 89 },
    { "optimization", "CombatHacking_Area_10_Perk_1", 90 },
    { "bartmosslegacy", "CombatHacking_Area_10_Perk_2", 91 },

    { "mechanic", "Crafting_Area_01_Perk_1", 92 },
    -- Not used
    { "", "Crafting_Area_01_Perk_2", 93 },
    { "truecraftsman", "Crafting_Area_02_Perk_1", 94 },
    { "scrapper", "Crafting_Area_02_Perk_2", 95 },
    { "workshop", "Crafting_Area_03_Perk_1", 96 },
    { "innovation", "Crafting_Area_04_Perk_1", 97 },
    { "sapper", "Crafting_Area_04_Perk_2", 98 },
    { "fieldtechnical", "Crafting_Area_05_Perk_1", 99 },
    { "200efficiency", "Crafting_Area_05_Perk_2", 100 },
    { "exnihilo", "Crafting_Area_06_Perk_1", 101 },
    { "efficientupgrade", "Crafting_Area_06_Perk_2", 102 },
    { "greasemonkey", "Crafting_Area_06_Perk_3", 103 },
    { "costoptimization", "Crafting_Area_07_Perk_1", 104 },
    { "lettherebelight", "Crafting_Area_07_Perk_2", 105 },
    { "wastenotwantnot", "Crafting_Area_08_Perk_1", 106 },
    { "tuneup", "Crafting_Area_08_Perk_2", 107 },
    { "edgerunnerartisan", "Crafting_Area_09_Perk_1", 108 },
    { "cuttingedge", "Crafting_Area_10_Perk_1", 109 },

    { "hailsofbullets", "Demolition_Area_01_Perk_1", 110 },
    { "pumpitlouder", "Demolition_Area_02_Perk_1", 111 },
    { "inyourface", "Demolition_Area_02_Perk_2", 112 },
    { "bloodrush", "Demolition_Area_03_Perk_1", 113 },
    { "deadcenter", "Demolition_Area_03_Perk_2", 114 },
    { "bulldozer", "Demolition_Area_04_Perk_1", 115 },
    { "mongoose", "Demolition_Area_04_Perk_2", 116 },
    { "momentumshift", "Demolition_Area_05_Perk_1", 117 },
    { "massacre", "Demolition_Area_05_Perk_2", 118 },
    { "skeetshooter", "Demolition_Area_06_Perk_1", 119 },
    { "heavyload", "Demolition_Area_06_Perk_2", 120 },
    { "unstopabble", "Demolition_Area_07_Perk_1", 121 },
    { "manic", "Demolition_Area_07_Perk_2", 122 },
    { "speeddemon", "Demolition_Area_08_Perk_1", 123 },
    { "burnbabyburn", "Demolition_Area_08_Perk_2", 124 },
    { "hitthedeck", "Demolition_Area_09_Perk_1", 125 },
    { "poppinoff", "Demolition_Area_09_Perk_2", 126 },
    { "biathlete", "Demolition_Area_10_Perk_1", 127 },
    -- Not used
    { "", "Demolition_Area_10_Perk_2", 128 },

    { "mechlooter", "Engineering_Area_01_Perk_1", 129 },
    { "blastshielding", "Engineering_Area_01_Perk_2", 130 },
    { "canttouchthis", "Engineering_Area_02_Perk_1", 131 },
    { "grenadier", "Engineering_Area_02_Perk_2", 132 },
    { "shrapnel", "Engineering_Area_03_Perk_1", 133 },
    { "bladerunner", "Engineering_Area_04_Perk_1", 134 },
    { "upto11", "Engineering_Area_04_Perk_2", 135 },
    { "lockandload", "Engineering_Area_04_Perk_3", 136 },
    { "biggerbooms", "Engineering_Area_05_Perk_1", 137 },
    -- Not used
    { "", "Engineering_Area_05_Perk_2", 138 },
    { "tesla", "Engineering_Area_06_Perk_1", 139 },
    { "lightningbolt", "Engineering_Area_06_Perk_2", 140 },
    { "ubercharge", "Engineering_Area_07_Perk_1", 141 },
    { "insulation", "Engineering_Area_07_Perk_2", 142 },
    { "gunwhisperer", "Engineering_Area_07_Perk_3", 143 },
    { "fuckallwalls", "Engineering_Area_08_Perk_1", 144 },
    { "playwithangles", "Engineering_Area_08_Perk_2", 145 },
    { "licketysplit", "Engineering_Area_09_Perk_1", 146 },
    { "jackpot", "Engineering_Area_10_Perk_1", 147 },
    { "superconductor", "Engineering_Area_10_Perk_2", 148 },

    { "gunslinger", "Gunslinger_Area_01_Perk_1", 149 },
    { "highnoon", "Gunslinger_Area_01_Perk_2", 150 },
    { "riobravo", "Gunslinger_Area_02_Perk_1", 151 },
    { "desperado", "Gunslinger_Area_02_Perk_2", 152 },
    { "onthefly", "Gunslinger_Area_03_Perk_1", 153 },
    { "longshotdroppop", "Gunslinger_Area_03_Perk_2", 154 },
    { "steadyhand", "Gunslinger_Area_04_Perk_1", 155 },
    { "okcorral", "Gunslinger_Area_04_Perk_2", 156 },
    { "vanishingpoint", "Gunslinger_Area_04_Perk_3", 157 },
    { "afistfulofeurodollars", "Gunslinger_Area_05_Perk_1", 158 },
    { "fromheadtotoe", "Gunslinger_Area_05_Perk_2", 159 },
    { "grandfinale", "Gunslinger_Area_06_Perk_1", 160 },
    { "acrobat", "Gunslinger_Area_06_Perk_2", 161 },
    { "attritionalfire", "Gunslinger_Area_07_Perk_1", 162 },
    { "wildwest", "Gunslinger_Area_07_Perk_2", 163 },
    { "snowballeffect", "Gunslinger_Area_08_Perk_1", 164 },
    { "westworld", "Gunslinger_Area_08_Perk_2", 165 },
    { "leadsponge", "Gunslinger_Area_09_Perk_1", 166 },
    { "brainpower", "Gunslinger_Area_10_Perk_1", 167 },

    { "bigsleep", "Hacking_Area_01_Perk_1", 168 },
    { "massvulnerability", "Hacking_Area_01_Perk_2", 169 },
    { "almostin", "Hacking_Area_02_Perk_1", 170 },
    { "advanceddatamine", "Hacking_Area_02_Perk_2", 171 },
    { "massvulnerabilityresistance", "Hacking_Area_03_Perk_1", 172 },
    { "extendednetworkinterface", "Hacking_Area_03_Perk_2", 173 },
    { "turretshutdown", "Hacking_Area_04_Perk_1", 174 },
    { "dataminemastermind", "Hacking_Area_04_Perk_2", 175 },
    { "totalrecall", "Hacking_Area_05_Perk_1", 176 },
    { "dataminevirtuoso", "Hacking_Area_06_Perk_1", 177 },
    { "turrettamer", "Hacking_Area_06_Perk_2", 178 },
    { "efficiency", "Hacking_Area_07_Perk_1", 179 },
    { "cloudcache", "Hacking_Area_07_Perk_2", 180 },
    { "massvulnerabilityquickhacks", "Hacking_Area_08_Perk_1", 181 },
    { "totallerrecall", "Hacking_Area_08_Perk_2", 182 },
    { "hackathon", "Hacking_Area_09_Perk_1", 183 },
    { "headstart", "Hacking_Area_09_Perk_2", 184 },
    { "compression", "Hacking_Area_10_Perk_1", 185 },
    { "bufferoptimization", "Hacking_Area_10_Perk_2", 186 },

    { "stinglikeabee", "Kenjutsu_Area_01_Perk_1", 187 },
    { "roaringwaters", "Kenjutsu_Area_01_Perk_2", 188 },
    { "crimsondance", "Kenjutsu_Area_02_Perk_1", 189 },
    { "slowandsteady", "Kenjutsu_Area_02_Perk_2", 190 },
    { "flightofthesparrow", "Kenjutsu_Area_03_Perk_1", 191 },
    { "offensivedefence", "Kenjutsu_Area_03_Perk_2", 192 },
    { "stuckpig", "Kenjutsu_Area_04_Perk_1", 193 },
    { "shiftingsands", "Kenjutsu_Area_04_Perk_2", 194 },
    { "blessedblade", "Kenjutsu_Area_05_Perk_1", 195 },
    { "unbokrnespirit", "Kenjutsu_Area_05_Perk_2", 196 },
    { "bloodlust", "Kenjutsu_Area_06_Perk_1", 197 },
    { "floatlikeabutterfly", "Kenjutsu_Area_06_Perk_2", 198 },
    { "fieryblast", "Kenjutsu_Area_07_Perk_1", 199 },
    { "judgejurtyandexecutioner", "Kenjutsu_Area_07_Perk_2", 200 },
    { "crimsontide", "Kenjutsu_Area_08_Perk_1", 201 },
    { "deathbold", "Kenjutsu_Area_08_Perk_2", 202 },

    { "silentanddeadly", "Stealth_Area_01_Perk_1", 203 },
    { "crouchingtiger", "Stealth_Area_01_Perk_2", 204 },
    { "hiddendragon", "Stealth_Area_02_Perk_1", 205 },
    { "daggerdealer", "Stealth_Area_02_Perk_2", 206 },
    { "strikefromtheshadows", "Stealth_Area_03_Perk_1", 207 },
    { "assassin", "Stealth_Area_03_Perk_2", 208 },
    { "legup", "Stealth_Area_03_Perk_3", 209 },
    { "sniper", "Stealth_Area_04_Perk_1", 210 },
    { "cutthroat", "Stealth_Area_04_Perk_2", 211 },
    { "cleanwork", "Stealth_Area_05_Perk_1", 212 },
    { "aggressiveantitoxins", "Stealth_Area_05_Perk_2", 213 },
    { "stunningblows", "Stealth_Area_05_Perk_3", 214 },
    { "ghost", "Stealth_Area_06_Perk_1", 216 },
    { "fromtheshadows", "Stealth_Area_06_Perk_2", 217 },
    { "commando", "Stealth_Area_07_Perk_1", 218 },
    { "rattlesnake", "Stealth_Area_07_Perk_2", 219 },
    { "venomousfang", "Stealth_Area_07_Perk_3", 220 },
    { "restorativeshaows", "Stealth_Area_08_Perk_1", 221 },
    { "hastyretreat", "Stealth_Area_08_Perk_2", 222 },
    { "silentfinisher", "Stealth_Area_08_Perk_3", 223 },
    { "neurotoxin", "Stealth_Area_09_Perk_1", 224 },
    { "cheatdeat", "Stealth_Area_09_Perk_2", 225 },
    { "hastentheinevitable", "Stealth_Area_09_Perk_3", 226 },
    { "restorativeshadows", "Stealth_Area_10_Perk_1", 227 }
}

function  gamedataPerkType.Get(perkName)
    perkName = perkName:lower():gsub("%W", "")
    for _, perkTable in ipairs(_gamedataPerkType) do
        if perkTable[1]:lower():gsub("%W", "") == perkName then
            return perkTable
        end
    end
end

-- Specify index as zero based.
function gamedataPerkType.GetPerkTableFromIndex(perkIndex)
    perkIndex = perkIndex + 1
    if perkIndex >= 1 and perkIndex <= #_gamedataPerkType then
        return _gamedataPerkType[perkIndex]
    end
end

function gamedataPerkType.GetAll()
    return _gamedataPerkType
end

return gamedataPerkType
